# Generated by Django 4.0.1 on 2022-02-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_discussion_host_blog_discussion_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-timeCreated', '-timeUpdated']},
        ),
    ]
