# Generated by Django 4.0.1 on 2022-02-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_discussion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='room',
            new_name='discuss',
        ),
    ]
